### ISSUE TITLE
implement inverse Weierstrass function

### ISSUE THREAD

**Issue by stla** [stla/pyweierstrass#1]

**Comment by stla** [comment]
@HeskethGD done

**Comment by HeskethGD** [comment]
Great! Thanks, I will check it out. I wonder if this version is correct up to a sign +/-. If I remember correctly it is necessary to specify wp prime in order to get the sign right. I think that is why Mathematica optionally accepts the derivative to get the unique point, as described in the Details part here: https://reference.wolfram.com/language/ref/InverseWeierstrassP.html

**Comment by stla** [comment]
I don't remember where I found this formula (maybe on the NIST site) but nothing was said about the sign.
